---
- name: Install required system packages
  ansible.builtin.apt:
    name: '{{ item }}'
    state: latest
  loop:
    - git
    - binutils

- name: Git clone efs-utils
  ansible.builtin.git:
    repo: 'https://github.com/aws/efs-utils'
    dest: /tmp/efs-utils

- name: Build amazon-efs-utils
  ansible.builtin.shell:
    cmd: ./build-deb.sh
    chdir: /tmp/efs-utils/

- name: Install amazon-efs-utils
  ansible.builtin.shell:
    cmd: 'apt-get install -y /tmp/efs-utils/build/amazon-efs-utils*deb'
    warn: false

- name: Create a directory for the mount
  file:
    path: "{{ aws_efs_path }}"
    state: directory
    mode: "{{ aws_efs_mode }}"
    owner: "{{ aws_efs_user }}"
    group: "{{ aws_efs_group }}"

- name: Mount the path
  mount:
    path: "{{ aws_efs_path }}"
    src: "{{ aws_efs_filesystem_id }}"
    fstype: efs
    opts: "_netdev,tls,accesspoint={{ aws_efs_access_point_id }}"
    state: mounted
